### ISSUE TITLE
Attack indicator doesn't show up

### ISSUE THREAD

**Issue by wilsondgonzales** [KurodaAkira/RPG-Hud#10]
With the latest version, the attack indicator doesn't render on the crosshair regardless of whatever debug options for crosshair is used

**Comment by Raelzaryn** [comment]
Sorry for responding so late. I've worked on my computer and haven't had time to work on this mod.
I'll look into it today and mot likely fix it.

**Comment by Raelzaryn** [comment]
I investigated it and in all MC version (except 1.8.9 ofc) it works.
Do you have anything else that might interfere with it?
