### ISSUE TITLE
1.18.2 Forge Clock is not working

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [KurodaAkira/RPG-Hud#101]
As title says, clock is not working. Regardless of what time it is or what settings you use, the clock will always show 06:00. I've also checked the logs and have found no error that would explain this issue.

**Comment by e-motiv** [comment]
I confirm.
Java Edition      ---     Forge 40.1.68      ---      Windows 10

**Comment by Raelzaryn** [comment]
fixed with 3.9.2 for 1.18.2 forge
