### ISSUE TITLE
not sure if this is your fault or not 

### ISSUE THREAD

**Issue by tiarnia** [KurodaAkira/RPG-Hud#11]
random crash 

[B#349]  // Why did you do that?
[B#349]  
[B#349]  Time: 5/25/17 8:48 PM
[B#349]  Description: Unexpected error
[B#349]  
[B#349]  java.lang.NullPointerException: ingredient cannot be null
[B#349]  	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
[B#349]  	at mezz.jei.ingredients.IngredientRegistry.getIngredientHelper(IngredientRegistry.java:86)
[B#349]  	at mezz.jei.gui.Focus.<init>(Focus.java:16)
[B#349]  	at mezz.jei.recipes.RecipeRegistry.createFocus(RecipeRegistry.java:204)
[B#349]  	at me.superckl.jet.RecipeGuiLogic.<init>(RecipeGuiLogic.java:59)
[B#349]  	at me.superckl.jet.handler.RenderTickHandler.onRenderTick(RenderTickHandler.java:47)
[B#349]  	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_889_RenderTickHandler_onRenderTick_Pre.invoke(.dynamic)
[B#349]  	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[B#349]  	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[B#349]  	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.pre(GuiIngameRPGHud.java:455)
[B#349]  	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.drawElement(GuiIngameRPGHud.java:626)
[B#349]  	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.func_175180_a(GuiIngameRPGHud.java:138)
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1089)
[B#349]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:124)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Raelzaryn** [comment]
First: sorry for not responding
Second: I'm not exactly sure what the problem is since the GuiIngameRPGHud file varies with each minecraft version. WHich version are you using? I need to know that in order to see if that problem lies with my mod or not.

**Comment by tiarnia** [comment]
Whatever the newest version for 1.11.2 is I'm not in front of my computer at the moment I can check it when I get home

**Comment by Raelzaryn** [comment]
I checked this a couple of times and it doesn't seem to be a problem from RPG-Hud
