### ISSUE TITLE
Crash when trying to shift-click an item from a chest to my inventory

### ISSUE THREAD

**Issue by brisingraerowing** [KurodaAkira/RPG-Hud#12]
[Crash Log](https://gist.github.com/BrisingrAerowing/b7747b5d8f5bf7b94476ec0483ab1d80)

I was in a village trying to loot a chest (I have a mod that adds additional buildings with chests to villages) using shift-clicking, and got this crash.

**Comment by Raelzaryn** [comment]
Sorry for not responding in a while. 
I just looked into this and fixed it. 
Unfortunatly this is only a temporary "fix" as the ItemPickup feature is far from being finished (need to figure out a good way of implementing it)
The update will go online with the next version (which will probably just add free scaling and the 1.12 version port)
