### ISSUE TITLE
Item pickup widget bug with Forestry installed

### ISSUE THREAD

**Issue by DoragonKeiyou** [KurodaAkira/RPG-Hud#14]
MC Version 1.10.2
RPG HUD Version 3.6.3
Forestry Version 1.01.2-5.2.17.377

When picking up an item you do not have in your inv, it works as intended.  If you pick up the same item when it's already in your inventory, it shows up as x0 instead of the amount picked up.

No idea the reason why this is, but my guess would have to be how the backpack system is handled.

**Comment by Raelzaryn** [comment]
Truthfully the item pickup is really work in progress and gives me more headache than it should. For now please disable it if you encounter gamebreaking issues. For the next versions I'll make it disabled by default til I fix it.

**Comment by askabaria** [comment]
Workaround:
Disabling backpacks in the forestry modules.cfg config file fixes the pickup showing x0 with no item.
