### ISSUE TITLE
Entity Inspect doesn't accept custom texture

### ISSUE THREAD

**Issue by MasterEnderman** [KurodaAkira/RPG-Hud#19]
I made some custom textures for the interfaces and the entity inspector and used the mod Resource Loader to add them in the game.
The interfaces just load fine, but the entity inspector reacted in a strange way. It only changed the texture of the border, where the mob shows up but nothing else.

Minecraft: 1.11.2
Forge: 13.20.1.2425
RPG-Hud: 3.6.3
Resource Loader: 1.5.2

If there are more questions, just ask.

**Comment by Raelzaryn** [comment]
There shouldn't be any difference.
I've never worked with ResourceLoader before (truthfully this is the first time I've heard of it).
But I haven't done anything different in the way I implement the entity inspect widget.

**Comment by Raelzaryn** [comment]
Some weird things happened with the texture. The path was incorrectly set (but still used the correct file?). I dont't exactly know what was going on but I changed it, could you tell me if that bug still persists in 3.6.4 (due in ~1-2h)

**Comment by MasterEnderman** [comment]
Thanks for the fix. Everything works fine now. Keep up the good work.
