### ISSUE TITLE
Crosshair rendering bug

### ISSUE THREAD

**Issue by jho5245** [KurodaAkira/RPG-Hud#23]
I'm korean so I can't explain this correctly.
In debug mode screen, the crosshair in the middle of the screen disappears.
And also in normal minecraft, the crosshair in non debug mode should be color reversal.
however the crosshair with this mod's color is set to white.
In a word, just look at the sun ingame with and wihtout using the mod.
Then you can figure it out what I'm talking about.

**Comment by Raelzaryn** [comment]
WIll look into it.

**Comment by Raelzaryn** [comment]
This is fixed with the next version (unfortunatly there are a few more bugs I intend to fix before a release)
