### ISSUE TITLE
Rendering collision with Better HUD mod

### ISSUE THREAD

**Issue by jho5245** [KurodaAkira/RPG-Hud#24]
Since the RPG-HUD mod doesn't render the HUD in creative mode, the feature also blocks rendering with the Better HUD's HUD screen. I tried in minecraft 1.12.1 with both two mods and only Better HUD mod.
Here's the Better HUD
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2314863-better-hud-1-3-9-adds-28-new-customisable-elements

**Comment by Raelzaryn** [comment]
You are using both RPG-HUD and Better HUD? And neither shows up?

**Comment by jho5245** [comment]
I tried with only those 2 mods and both two mod's HUD don't be seen in creative mode.
Maybe RPG-HUD forces not to be seen its HUD and other mods HUD.

**Comment by jho5245** [comment]
I think this may be fixed if you add the toggle feature so that I can see the RPG HUD when I'm creative mode. maybe collision of rendering priority.

**Comment by jho5245** [comment]
I think this may be fixed if you add the toggle feature so that I can see the RPG HUD when I'm creative mode. maybe collision of rendering priority.

**Comment by jho5245** [comment]
I think this may be fixed if you add toggle feature to render the HUD in creative mode.

**Comment by Raelzaryn** [comment]
this is fixed with 3.7. RPG-Hud no longer overwrites events. If better HUD uses the appropiate events for rendering, it will work.
