### ISSUE TITLE
[1.12.1] Scaling Health Minor Issue

### ISSUE THREAD

**Issue by Preminenc3** [KurodaAkira/RPG-Hud#25]
For Scaling health the problem is with the Modern HUD once you get to health that is 100 or above the number is offset from the GUI.
 
[Scaling Health Issue Image](http://i.imgur.com/G1NCy62.png)

**Comment by Raelzaryn** [comment]
Thanks for also posting it here. Will look into it  :)

**Comment by Raelzaryn** [comment]
This is now fixed with the next version (I'll most likely upload it today)
