### ISSUE TITLE
[1.12.1] Modern HUD Simple Offset Issue

### ISSUE THREAD

**Issue by Preminenc3** [KurodaAkira/RPG-Hud#26]
The armor stat goes over the health is offset.

[Image](http://i.imgur.com/sytUnuP.png)

**Comment by Raelzaryn** [comment]
you are the first person (that I know off) to use the normal health.
So I haven't encountered this yet. Will fix it.

**Comment by Raelzaryn** [comment]
Should've been fixed with 3.7
