### ISSUE TITLE
Client crashing when selecting a bow in the hotbar

### ISSUE THREAD

**Issue by Guardian9978** [KurodaAkira/RPG-Hud#3]
Here's a crashlog:
http://pastebin.com/UHGLFDZB

MC Version: 1.10.2
Forge Version: 12.18.3.2185
RPG Hud Version: 3.3

Let me know if you need more information.

**Comment by loander** [comment]
same here, the problem started yesterday.

**Comment by KurodaAkira** [comment]
I'll try to figure out what's wrong.
But to recreate it, do you have arrows in you inventory? If so. Where?

**Comment by loander** [comment]
no arrows in inventory

**Comment by loander** [comment]
just bow

**Comment by KurodaAkira** [comment]
Thanks. I recreated it - and fiuxed it.
I'll fix 2 more bugs then I'll release the version. SHould be within the next hour.

**Comment by Guardian9978** [comment]
It appears to still be an issue.
Crash Log: http://pastebin.com/EvKVzHr4

Mod Version 3.3.1

The bow I'm trying to select is from Botania its the Crystal Bow
Crystal Bow: https://ftbwiki.org/Crystal_Bow

When I try to select it without arrows in my inventory I crash.

**Comment by KurodaAkira** [comment]
This is really getting weird. It worked when I fixed it. Now it doesn't work again o.o.
I'll fix that for sure this time - I hope...

**Comment by KurodaAkira** [comment]
I'm honestly sorry about this (and that it took me 10 days to notice it. I must have completly overlooked it - I didn't ignroe it. Just didn't know this bug existed - I'm not a bow fan).
Is there any feature you want to see? If so please tell me and I'll put it high on my priority list (if I'll implement it)

**Comment by Guardian9978** [comment]
I can't think of anything to add. Thank you for this lovely hud mod.

**Comment by loander** [comment]
I have a suggestion! If its possible can you add target healthbar to show
on right corner. Like target name (portret if possible) and health. :)

2017. gada 17. febr. 22:15, "Guardian9978" <notifications@github.com>
rakstīja:

**Comment by loander** [comment]
I have a suggestion! If its possible can you add target healthbar to show
on right corner. Like target name (portret if possible) and health. :)

2017. gada 17. febr. 22:12, "KurodaAkira" <notifications@github.com>
rakstīja:

**Comment by KurodaAkira** [comment]
YOu mean something like what the old damage indicator did?
[*Link to the old thread*](http://minecraft-forum.net/minecraft-mods-downloads/1-6-2-damage-indicators-mod-download-2-2/#.WKdhQfKpf9A)
If so. I'll add it with the next version (was planned anyways) after the one I'm making currently (fixing that bug, adding 2 new small features - upload should be in very soon, maybe even this hour - just gotta test a few things first)

**Comment by loander** [comment]
Yes exacly :) also will it show how much health the target has if it has more than 20hp( like customnpc where you can set how much hp the npc has)?

**Comment by loander** [comment]
also is it possible to sync the server config with client? for example I dont want players to have compass and clock bar if they dont have those items.

**Comment by KurodaAkira** [comment]
I'll add a damage indicator like that very soon.

About the server-client syncing: I have honestly no idea about server-client communications, so I can't really tell you if that'll happen or not. I first need the time to figure all that out - or find someone who could help me with it.

**Comment by loander** [comment]
Thank you :) the server sync is just if possible, other way that I can
suggest that server owners would be happy if there would be a way to
disable editing of the config (like a line (true/false) in the config file
that cannot be changed in-game... I could think of many suggestions if
needed :)

2017. gada 18. febr. 01:29, "KurodaAkira" <notifications@github.com>
rakstīja:

**Comment by KurodaAkira** [comment]
it IS possible, I know that. I just don't know how x)
There are other mods that do this, so I just need to learn it. But I don't have much time. SO I really can't say when I'll do it.
