### ISSUE TITLE
Crosshair doesn't render in debug mode screen (F3)

### ISSUE THREAD

**Issue by jho5245** [KurodaAkira/RPG-Hud#33]
In non-debug mode screen the crosshair works as well as normal minecraft.
But if I press F3, to debug mode screen, the crosshair disappears. Please check it out.
I also tried all of settings that have relevance to crosshair.
I only used RPG HUD mod.

**Comment by Raelzaryn** [comment]
Duplicate: https://github.com/KurodaAkira/RPG-Hud/issues/23
Also this is fixed with 3.6.5.
At least when I tested it.

#Edit: Upon closer inspection, it seems I only fixed this bug with 1.10.2 and forgot to implement it on the others. I'll upload a fix momuntarily.

**Comment by Raelzaryn** [comment]
In the future, please reopen the original issue instead of creating a new one
