### ISSUE TITLE
mcmod.info hasn't been pushed to the version on curse, maybe they just have a late commit?

### ISSUE THREAD

**Issue by JustJinxed** [KurodaAkira/RPG-Hud#36]
Grabbed the most recent version off curse (3.6.6.1) and it's got this in the mcmod.info file. 

[
{
  "modid": "examplemod",
  "name": "Example Mod",
  "description": "Example placeholder mod.",
  "version": "3.6.6.1",
  "mcversion": "1.12.1",
  "url": "",
  "updateUrl": "",
  "authorList": ["ExampleDude"],
  "credits": "The Forge and FML guys, for making this example",
  "logoFile": "",
  "screenshots": [],
  "dependencies": []
}
]

Is it just an old version of the file, or is something breaking in your gradle? (I see the local GIT version is fine)

**edit: as such, I can't open the config options for the mod itself. :(

**Comment by Raelzaryn** [comment]
I was aware of it. and I release a new version (3.6.6.2 for 1.12.X) that has this fixed. And it's one file for all 1.12 versions again.
