### ISSUE TITLE
[1.12.x/Forge/LiteLoader] Conflict with TabbyChat 2

### ISSUE THREAD

**Issue by NovaViper** [KurodaAkira/RPG-Hud#38]
I notice when I use this mod in conjunction with TabbyChat 2, RPG HUD's chat ends up overriding this mod. It ends up looking like this:
![2017-10-15_16 58 52](https://user-images.githubusercontent.com/7191115/31589625-308b5764-b1ca-11e7-8e13-a4cc148a595d.png)

Instead of like this:
![2017-10-15_17 02 48](https://user-images.githubusercontent.com/7191115/31589650-b2b5085c-b1ca-11e7-83cc-36fcd5a16f0d.png)

I also can't seem to turn off RPG Hud's rendering system in order to let TabbyChat 2 render.

**Comment by NovaViper** [comment]
I made an [issue](https://github.com/killjoy1221/TabbyChat-2/issues/84) regarding the same problem on TC2's issue page.

**Comment by Raelzaryn** [comment]
This problem is known to me and was previously fixed (there is a setting for it - something like render vanilla chat). Have you tried that? As far as I know that should do the trick.

**Comment by NovaViper** [comment]
I tried that, even using the prevent rendering option and it still uses RPG Hud's chat design instead of TC2

**Comment by NovaViper** [comment]
Actually, what ends up happening when I use the Prevent rendering option, it makes the entire chat box vanish

**Comment by NovaViper** [comment]
I played around with the settings more and fixed the bug. I had to turn on Force Render and Render Vanilla Element in order to make the gui not vanish. Thanks for the tip!
