### ISSUE TITLE
Rpg-Hud Broken Display issue.

### ISSUE THREAD

**Issue by JustLiam040** [KurodaAkira/RPG-Hud#39]
I cant say i'm 100% sure what is causing this to happen, i'm using RPG-HUD in  my custom modded pack that is currently for private use only. However, the pack itself contains 138 mods, including RPG-HUD and other mods child mods. Thus making it a medium sized pack. I'm not sure why, but this display issue is constant and i cant seem to figure out whats doing it? i tried disabling EVERY event i could to see if something was overriding it, but alas, nothing. As you can see in the top left (i'm using the modern layout) the health bar is like, phasing into the hunger? and i've no idea what is causing this to happen. I'f you're wondering why the compass looks weird its because i'm using the true font mod.
![2017-10-24_16 51 14](https://user-images.githubusercontent.com/33065753/31954188-cb403dba-b8dc-11e7-86cb-45cb21c898a9.png)

**Comment by Raelzaryn** [comment]
This issue is known. it's caused by mods like tinkers' or scaling health. Go to settings -> Health -> prevent event. If this doesn't fix it let me know. because it did for my tests.

**Comment by JustLiam040** [comment]
I do apologise if this is a known bug, i searched through majority of issues on here, albeit not many. And i also apologise that this was a duplicate, i couldn't find a similar bug anywhere. unfortunately changing this setting did not fix it for me, i was aware of this setting and it was one of the methods i tried, however, as mentioned, upon "preventing event" for every available ones (even ones that would have no effect such as 'horse jump bar') this issue still persisted. I will try removing tinkers from the pack and will let you know if different results emerge.

P.S, thank you so much for the insanely quick reply, that was way quicker than i imagined.

**Comment by JustLiam040** [comment]
Thank you so much for the quick reply, i was very eager to get this fixed because i really wanted it in the modpack. Turns out i had the wrong setting enabled so instead of having prevent event i had prevent render enabled. Again, thank you so much for the quick reply.
