### ISSUE TITLE
Probleme mit anderen Mods

### ISSUE THREAD

**Issue by ChrisWeymann** [KurodaAkira/RPG-Hud#4]
Hi Akira,
erstmal nebenbei ist ein klasse Mod, gefällt mir richtig gut.

Jetzt aber zu meinem kleinen Problem.
In den debug Einstellungen kann man ja so ziemlich alles ein und ausschalten.
Nur leider nicht, dass der Chat beeinflusst wird. Aber genau dieser macht Probleme in Verbindung mit TabbyChat2 ( https://github.com/killjoy1221/TabbyChat-2 )
Im Grunde ersetzt TabbyChat2 den Chat komplett, dies funktioniert nicht solange „RPG-Hud“ installiert ist.
Wäre es möglich dies auch noch mit einzubauen, wie die anderen debug Optionen es auch ermöglichen den Vanilla Chat zu nutzen? Währe echt klasse.

Mit freundlichen Gruß
Christopher

**Comment by KurodaAkira** [comment]
Ich habe keine Einstellung für den Chat hinzugefügt? Muss ich wohl vergessen haben.
Mit dem nächsten update (vermutlich morgen - wird allerdings ne beta version, da ich die mod nicht gut testen kann) dann hinzugefügt.

**Comment by KurodaAkira** [comment]
The new version is out now. With the added debug options for the chat element (Enable Force Vanilla to use the vanilla element which should get overrriden by tabby chat if I read it's source code correctly)

**Comment by ChrisWeymann** [comment]
Ja funktioniert :)
Danke :+1:

**Comment by KurodaAkira** [comment]
Gut. Wenn du etwas anderes stößt, was nicht richtig funktioniert oder du gerne in der Mod hättest, lass es mich wissen.
