### ISSUE TITLE
[1.12.2] Armor HUD Underlay Issue (Modern HUD)

### ISSUE THREAD

**Issue by Preminenc3** [KurodaAkira/RPG-Hud#40]
[Edit] It seems like it's an issue with Tinkers Construct Weapons

The black/gray underlay constricts to the item with the lowest durability [image](https://i.imgur.com/y1G0QDV.png). As seen in the image the sword has the lowest durability so it contracts to it, but when I unequip the sword it goes back to normal and works fine since they all have 3 digit durability. 

How To Fix: I am not sure if this is possible, but I would think would work is to first make it constrict to the largest digit durability rather than the smallest, and then center the other durabilities in that length.

**Comment by Raelzaryn** [comment]
I was under the assumption I already fixed this. Appears I was mistaken. I'll fix it.

**Comment by Preminenc3** [comment]
I am not sure if you saw my edit or not, but it is only a problem with Tinkers Construct Weapons.

**Comment by Raelzaryn** [comment]
There was an issue with the length calculation. Should be fixed since 3.6.9
