### ISSUE TITLE
[1.12.2] Possible conflict with all shaders

### ISSUE THREAD

**Issue by NovaViper** [KurodaAkira/RPG-Hud#41]
For the strangest reason, whenever I'm in Survival Mode, have the Entity Inspect option turned _on_, and have an entity leashed, my screen either does REALLY dark, turns completely blue, or the experience bar at the bottom completely vanishes. This issue began [here](https://github.com/capnkirok/animania/issues/451) however it was discovered that it was this mod that is causing these strange issue.

OS: Windows 10 Home Edison 64-Bit
Graphics Card: Intel HD Graphics 4400
OpenGL Version and Build: 4.3.0 - 20.19.15.4531
RAM: 8GB

**Comment by Raelzaryn** [comment]
I tried to recreate this on my end. Thus far without any success. Can you give me your mod list?

**Comment by NovaViper** [comment]
Here: https://pastebin.com/tAb47cZV

**Comment by NovaViper** [comment]
Huh, I did just finish building my new PC with a GeForce GTX 1060, and that bug seemed to have gone away entirely. Guessing it was my old PC's integrated GPU

**Comment by GreenShaman** [comment]
I think this occurs when shaders are active, I experienced this too.
