### ISSUE TITLE
Vanilla render element refusing to comply. [1.10.2]

### ISSUE THREAD

**Issue by JustLiam040** [KurodaAkira/RPG-Hud#42]
To add some reasoning as to why, i would like to use the vanilla experience bar as i find the modern one a bit invasive. I have tried multiple combinations of settings eg. "Render vanilla element - true combined with render element- false" This does not render the modern or the vanilla element. If i switch the combination to "Render vanilla element -true combined with render element - true" it then completely ignores the vanilla element and renders the modern one instead. 

This issue is most likely down to my little understanding of the settings integrated with the mods. Any suggestions would be greatly appreciated. Apologies if this is a duplicate, i could not find a similar issue.

![2018-01-16_16 36 09](https://user-images.githubusercontent.com/33065753/35000421-4c1152a8-fadc-11e7-9dc9-dee7455aa54c.png)

**Comment by Raelzaryn** [comment]
Using a different exp bar for the modern hud is currently not possible and will not be possible anytime soon.
You could use the 3.7 option to force render the vanilla exp bar but it might be overlapping with the hotbar.
