### ISSUE TITLE
[1.12.2] Tough as Nails Thirst render conflicts

### ISSUE THREAD

**Issue by NovaViper** [KurodaAkira/RPG-Hud#47]
Forge Version: 14.23.4.2705
RPG Hud Version: 3.6.6.2
Tough as Nails Version: 3.1.0.115
Minecraft Version: 1.12.2

For some reason, whenever I have Thirst enabled in Tough as Nails and have RPG-Hud installed, the thirst bar only appears whenever I'm underwater. The issue doesn't occur when I have RPG Hud not installed.

**Comment by NovaViper** [comment]
This issue happens on pretty much all UI types

**Comment by Raelzaryn** [comment]
As Tough as Nails is discontinued, I will close the thread.
I changed some things with 3.7 of my mod which should take care of this issue nonetheless.
