### ISSUE TITLE
Render Crash

### ISSUE THREAD

**Issue by LokyLive** [KurodaAkira/RPG-Hud#5]
Hey man

First thing i love your HuD really awesome job ,p

I got a crash when i shot with my bow and i turn off arrow

**Comment by KurodaAkira** [comment]
Thank you for reporting this issue. But to be able to do something about it I will need to know which version you are running (which minecraft version and which version of this mod).
If you could also include the crash log (usually found in your ".minecraft/crash-logs" folder - post the one that got logged when my mod crashed it)

**Comment by LokyLive** [comment]
Release version  [1.10.2] RPG-HUD-3.5.2

Crash Report : https://pastebin.com/k9LwCnb4

**Comment by KurodaAkira** [comment]
Thank you for the crash log. 
While I couldn't replicate the bug I think I found the issue and fixed it with the just release 3.6 version.

**Comment by LokyLive** [comment]
thanks ,p

**Comment by KurodaAkira** [comment]
So it's fixed now?

**Comment by LokyLive** [comment]
i've just test few times and it is fixed . thanks so much
