### ISSUE TITLE
Version 3.6.7 Crash

### ISSUE THREAD

**Issue by Boskosauce** [KurodaAkira/RPG-Hud#57]
After updating from 3.6.6.2 to 3.6.7 for 1.12.2, I started to experience a crash.

Crash log: https://pastebin.com/mzCu3kX2

Any ideas? The crash comes after attempting to connect to my server. The log DOES mention some other details regarding terrain gen, if I'm reading this correctly, so it may not be the mod itself. However, if I downgrade, I can connect without issue.

**Comment by Raelzaryn** [comment]
Will see if I can replicate the issue

**Comment by Raelzaryn** [comment]
Can you provide me with your rpg-hud config? I am unable to replicate the error.

**Comment by Boskosauce** [comment]
I still experienced the crash even after deleting the config and regenerating a new one. I'll do some testing on my end, regarding the possibility of it being the world-type.

**Comment by Boskosauce** [comment]
Practically the same crash. Occurs in single player as well.

I made a new instance in the Twitch App with the following mods: https://i.imgur.com/Tk8aWpC.png

The crash still occurred.

**Comment by Raelzaryn** [comment]
Can you contact me via discord so we can get together a proper modlist for me to do tests with?
I am honestly having trouble finding all the mods you have installed.

**Comment by Boskosauce** [comment]
-deleted-

**Comment by Raelzaryn** [comment]
https://github.com/KurodaAkira/RPG-Hud/commit/7299035a6b0a6fd020b0c24e44e19c602d50d390
