### ISSUE TITLE
Changing Item in main hand while holding food in off hand causes crash

### ISSUE THREAD

**Issue by thephoenixlodge** [KurodaAkira/RPG-Hud#6]
https://pastebin.com/9R8f2dFp
Found with 3.5.2, as yet have not had the chance to test with 3.6+
Seems to be somewhat inconsistent, first time it was encountered was with pineapples from Plants, then with Peaches from Terraqueous, yet then didn't crash with vanilla apples. Has been observed to occur when changing item simply by scrolling across the hotbar, and by placing the held item (specifically observed with a jungle wood boat)

**Comment by ADeathlyTouch** [comment]
I was able to replicate by simply switching steak into my off hand and scrolling. Happened almost instantly and honestly surprised me how easy it was to replicate. This was done moments ago using version 3.6.1

**Comment by KurodaAkira** [comment]
I'll take a look tomorrow (3am here).
If I can find the problem (should be easy enough) I'll release the fix probably 1-2h later

**Comment by KurodaAkira** [comment]
Found the issue (crash when holding food in off hand while having less than maximum hunger and having no item in the main hand). I didn't properly check for that case. It's fixed now. Just gotta wait for curse to accept and check the 3.6.2 version.
