### ISSUE TITLE
Gun completely disappeared after swapping hands

### ISSUE THREAD

**Issue by Primal-Ursus** [KurodaAkira/RPG-Hud#63]
I wanted to test whether you could wield guns in either hand however after swapping back (using the VSS) my gun seeming has been removed. The gun was acquired from a bandit if that matters

This is reproducible by simply putting a weapon in your offhand and attempting it aim/fire 

Version: MW 2.0 Contagion v0.4.4.6 mc1.12.2
Mods Included:
![image](https://user-images.githubusercontent.com/18637004/87579804-6cd9d800-c6ce-11ea-9448-22d917290583.png)

**Comment by Raelzaryn** [comment]
The issue only happens with RPG-Hud installed? Which RPG-Hud version are you using?

**Comment by Primal-Ursus** [comment]
Please close and ignore me, I don't have RPG Hud installed I mistook the other requests as the Modern Warfare mod github

**Comment by Raelzaryn** [comment]
Did you google the github page or how did you end up here instead?

**Comment by Primal-Ursus** [comment]
Googled the issue, saw this github came up with a plethora of other Vics Modern Warfare mod issues that looked similar and thought I'd add a ticket, leapt to conclusions sorry

**Comment by Raelzaryn** [comment]
No problem. I hope your issue gets fixed.
