### ISSUE TITLE
fabric 1.16.1 - config button clips out of screen on all menus (including title screen)

### ISSUE THREAD

**Issue by Linguardium** [KurodaAkira/RPG-Hud#65]
![2020-07-24_09 25 02](https://user-images.githubusercontent.com/61733861/88413433-0751af80-cd90-11ea-8e7d-d675c8110c49.png)

**Comment by Raelzaryn** [comment]
this seems to be a mod conflict. I am not able to recreate it. Can you give me a list of your mods?

**Comment by Linguardium** [comment]
will do, i'll attempt to strip it down to just what causes it, first. thanks for looking.

**Comment by Raelzaryn** [comment]
I found the culprit: Mod Menu
I'll have a look if I can fix this on my end.

**Comment by Raelzaryn** [comment]
I created a work around. It's not the prettiest thing but goes around this by pushing the button down by 12 if the modmenu main class is detected. At a later point I will look into adding support for the menu.
This "fix" is available now with 3.7.7
