### ISSUE TITLE
Crashes on Server

### ISSUE THREAD

**Issue by CanBoy67** [KurodaAkira/RPG-Hud#72]
Now this may just be my stupidity but whenever I load this mod on my server it crashes with "java.lang.RuntimeException: Attempted to load class net/spellcraftgaming/rpghud/main/ModRPGHud for invalid dist DEDICATED_SERVER" and the crashlog is [here](https://pastebin.com/TwwnEMqA), this is an fml crash

**Comment by bandolero30** [comment]
the same fail here, some news?

**Comment by Raelzaryn** [comment]
well. this is not really an issue or problem on my end.
The mod is entirely client-side, meaning it should not be installed on a server (it works regardless).
Just remove it from the server-side mods folder and you're good.
