### ISSUE TITLE
Fabric 1.17

### ISSUE THREAD

**Issue by KosmX** [KurodaAkira/RPG-Hud#79]
Here is a 1.17 Fabric update: [KosmX/RPG-Hud at MC-Fabric-1.17](https://github.com/KosmX/RPG-Hud/tree/MC-Fabric-1.17)
Compiling, probably won't crash
I don't do a PR as this should be on a new branch...
:D

**Comment by Andre601** [comment]
Do you have a jar to test out?

**Comment by KosmX** [comment]
I've uploaded the jar to the releases.
[KosmX/RPG-Hud releases](https://github.com/KosmX/RPG-Hud/releases/tag/3.8.1)
