### ISSUE TITLE
Shifted chat leads to desynced position for links in chat

### ISSUE THREAD

**Issue by thephoenixlodge** [KurodaAkira/RPG-Hud#9]
As per the title, if using a hud type that shifts the chat, the point where you would have to click to use a link in chat is still in the unshifted position, which makes clicking them annoying at best.

**Comment by Raelzaryn** [comment]
I'll look into it once I've finished setting my new PC up^^
Give me 1 or 2 days.

**Comment by Raelzaryn** [comment]
This was slightly more than 1 or 2 days. Sorry for that.
I'm finishing up 3.6.4 right now (pure bugfix version) which contains a fix to this.
